USE MASTER
GO

CREATE DATABASE MasterBase
GO

USE MasterBase
GO

CREATE DATABASE dbo.Type(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Name VARCHAR(50) NOT NULL
);
GO

CREATE DATABASE dbo.Age(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Age INT NOT NULL
);
GO

CREATE DATABASE dbo.Supplier(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Features NVARCHAR(MAX)
);
GO

CREATE DATABASE dbo.Whiskey(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Code uniqueidentifier = NEWID(),
	Name VARCHAR(50) NOT NULL,
	Type_id INT NOT NULL,
	Age_id INT NOT NULL,
	Photo VARBINARY(MAX) NOT NULL,
	Price MONEY NOT NULL,
	Supplier_id INT NOT NULL,
	FOREIGN KEY (Type_id) REFERENCES dbo.Type(Id),
	FOREIGN KEY (Age_id) REFERENCES dbo.Age(Id),
	FOREIGN KEY (Supplier_id) REFERENCES dbo.Supplier_id(Id)
);
GO

CREATE DATABASE WhiskeyReviews(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	User_id INT NOT NULL,
	Review VARCHAR(50) NOT NULL,
	Whiskey_id INT NOT NULL,
	FOREIGN KEY (Whiskey_id) REFERENCES dbo.Whiskey(Id)
);
GO